spring.datasource.url=jdbc:h2:mem:project
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.mvc.servlet.path=/api/v1
server.port=8081

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.graphql.cors.allowed-origins=http://localhost:4200
spring.graphql.cors.allowed-methods=*

# JWT Configuration
app.jwt.secret=ChoufliHalHVACPlatformSecretKey2026VerySecureAndLongEnoughForHS512Algorithm
app.jwt.expiration=86400000
